Repository shahzebsiddiqui/jobstats, pull requests merged in 2021-04, with the labels that each got.

#2 add python 3.X support
  jobstats
Labels: size/L

#3 add version option
  README.rst
  jobstats
Labels: size/S

#4 output of some text was in 'byte', this needs to be decoded into string
  jobstats
Labels: size/XS
